# Generated by Django 4.0.2 on 2022-02-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=300)),
                ('material_name', models.CharField(max_length=300)),
                ('material_image', models.CharField(max_length=300)),
                ('material_supplierlink', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=300)),
                ('product_description', models.CharField(max_length=500)),
                ('product_image', models.FileField(upload_to=None)),
                ('product_materialsused', models.CharField(max_length=300)),
                ('product_quantity', models.IntegerField(max_length=10)),
                ('product_unitprice', models.IntegerField(max_length=10)),
                ('product_type', models.CharField(max_length=300)),
                ('product_visibility', models.BooleanField(max_length=300)),
                ('product_colors', models.CharField(max_length=300)),
            ],
        ),
    ]
