# Generated by Django 3.2 on 2022-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frankiesapp', '0002_auto_20220228_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_unitprice',
            field=models.IntegerField(),
        ),
    ]
