# Generated by Django 4.0.2 on 2022-03-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frankiesapp', '0002_alter_product_product_description'),
        ('frankiesapp', '0003_auto_20220228_1529'),
    ]

    operations = [
    ]
