# Generated by Django 4.0.2 on 2022-03-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frankiesapp', '0003_auto_20220228_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_unitprice',
            field=models.PositiveIntegerField(),
        ),
    ]
