# Generated by Django 4.0.2 on 2022-03-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frankiesapp', '0004_alter_product_product_quantity_and_more'),
        ('frankiesapp', '0004_merge_20220301_1735'),
    ]

    operations = [
    ]
