# Generated by Django 4.0.2 on 2022-03-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frankiesapp', '0004_alter_product_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='toProcess/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_visibility',
            field=models.BooleanField(blank=True, max_length=300),
        ),
    ]
