# Generated by Django 4.0.2 on 2022-03-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frankiesapp', '0005_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_visibility',
            field=models.BooleanField(),
        ),
    ]
