# Generated by Django 4.0.2 on 2022-03-02 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frankiesapp', '0005_merge_20220301_2347'),
        ('frankiesapp', '0007_alter_product_product_visibility'),
    ]

    operations = [
    ]
